### PR TITLE
Testing Enumerable methods

### PR DESCRIPTION
**Pull request by CalyCherkaoui**
Here we tested all the methods in the Module Enumerable.
We used Rspec for the testing.

### CODE REVIEW

**Review by nikasulo — COMMENTED** [review]
# Hey team! 
I see your attempts to make some changes to this project, however the problems still persist. Do you mind messaging me on Slack so I can explain what you need and we may even schedule a Zoom meeting? Please let me know before your next submission so you don't keep going back and forth and spending much more of your time.

If I don't reply quickly on slack, try me on [Twitter](https://twitter.com/oluwadamilareo_)

**Comment by lekegitrepo** [comment]
#### Hi @CalyCherkaoui and @angel-mora :clap: :clap:
#### Well done. Two of the tests are still failing, check my comment below.

**_1. `numbers = [5, 9, 2, 3, 415, 6, 98]` so  `numbers.my_inject(:+)` is failing_**

**_2. Also, this is failing` (5..10).my_inject(:+)`_**

**_Consider adding `source 'https://rubygems.org'` to the gem file._**

**_Remove all the commented codes._**

#### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by lekegitrepo** [comment]
#### Good job Team :clap: :clap:
#### Well done for implementing the required changes. This project is approved :star:

**_Note: remove the commented on line 119 in the enumerables.rb file. Also, I don't know if this is going to be helpful, you can improve the `multiply_els` method to something like this:_**

```
def multiply_els(arr)
     arr.my_inject(:*)
    end
```

**_and add test_**

  ```
 context 'multiply_els method' do
      it 'multiply_els' do
        output = multiply_els([1, 3, 2])
        expect(output).to eql(6)
      end
    end
```

#### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approve

**Pull request merged**
